Collecting matplotlib==3.6.2
  Downloading matplotlib-3.6.2-cp39-cp39-win_amd64.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 65.1 kB/s eta 0:00:00
Requirement already satisfied: fonttools>=4.22.0 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (4.34.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (1.4.4)
Collecting pyparsing>=2.2.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     --------------------------------------- 98.3/98.3 kB 98.9 kB/s eta 0:00:00
Requirement already satisfied: pillow>=6.2.0 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (9.3.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (2.8.2)
Requirement already satisfied: numpy>=1.19 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (1.23.5)
Requirement already satisfied: packaging>=20.0 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (22.0)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp39-cp39-win_amd64.whl (160 kB)
     ------------------------------------- 160.2/160.2 kB 36.4 kB/s eta 0:00:00
Requirement already satisfied: cycler>=0.10 in c:\users\31kus\anaconda3\lib\site-packages (from matplotlib==3.6.2) (0.11.0)
Requirement already satisfied: six>=1.5 in c:\users\31kus\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib==3.6.2) (1.16.0)
Installing collected packages: pyparsing, contourpy, matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.2
    Uninstalling matplotlib-3.5.2:
      Successfully uninstalled matplotlib-3.5.2
Successfully installed contourpy-1.0.7 matplotlib-3.6.2 pyparsing-3.0.9
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-object-detection-api 0.1.1 requires contextlib2, which is not installed.
tensorflow-object-detection-api 0.1.1 requires Cython>=0.28.1, which is not installed.
tensorflow-object-detection-api 0.1.1 requires jupyter, which is not installed.
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
Collecting tensorflow==2.10.1
  Downloading tensorflow-2.10.1-cp39-cp39-win_amd64.whl (455.9 MB)
     -------                               98.3/455.9 MB 140.1 kB/s eta 0:42:32
Output exceeds the size limit. Open the full output data in a text editor
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\31kus\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 437, in _error_catcher
    yield
  File "C:\Users\31kus\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\31kus\anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 526, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\31kus\anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Users\31kus\anaconda3\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "C:\Users\31kus\anaconda3\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\31kus\anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\31kus\anaconda3\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\31kus\anaconda3\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:
...
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
Requirement already satisfied: opencv-python==4.6.0.66 in c:\users\31kus\anaconda3\lib\site-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.14.5 in c:\users\31kus\anaconda3\lib\site-packages (from opencv-python==4.6.0.66) (1.23.5)
Collecting imageio==2.23.0
  Downloading imageio-2.23.0-py3-none-any.whl (3.4 MB)
     ---------------------------------------- 3.4/3.4 MB 4.9 MB/s eta 0:00:00
Requirement already satisfied: pillow>=8.3.2 in c:\users\31kus\anaconda3\lib\site-packages (from imageio==2.23.0) (9.3.0)
Requirement already satisfied: numpy in c:\users\31kus\anaconda3\lib\site-packages (from imageio==2.23.0) (1.23.5)
Installing collected packages: imageio
Successfully installed imageio-2.23.0
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
Requirement already satisfied: gdown==4.6.0 in c:\users\31kus\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: beautifulsoup4 in c:\users\31kus\anaconda3\lib\site-packages (from gdown==4.6.0) (4.11.1)
Requirement already satisfied: filelock in c:\users\31kus\anaconda3\lib\site-packages (from gdown==4.6.0) (3.9.0)
Requirement already satisfied: six in c:\users\31kus\anaconda3\lib\site-packages (from gdown==4.6.0) (1.16.0)
Requirement already satisfied: requests[socks] in c:\users\31kus\anaconda3\lib\site-packages (from gdown==4.6.0) (2.28.1)
Requirement already satisfied: tqdm in c:\users\31kus\anaconda3\lib\site-packages (from gdown==4.6.0) (4.64.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\31kus\anaconda3\lib\site-packages (from beautifulsoup4->gdown==4.6.0) (2.3.2.post1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\31kus\anaconda3\lib\site-packages (from requests[socks]->gdown==4.6.0) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\31kus\anaconda3\lib\site-packages (from requests[socks]->gdown==4.6.0) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\31kus\anaconda3\lib\site-packages (from requests[socks]->gdown==4.6.0) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\31kus\anaconda3\lib\site-packages (from requests[socks]->gdown==4.6.0) (1.26.14)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\31kus\anaconda3\lib\site-packages (from requests[socks]->gdown==4.6.0) (1.7.1)
Requirement already satisfied: colorama in c:\users\31kus\anaconda3\lib\site-packages (from tqdm->gdown==4.6.0) (0.4.6)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\31kus\anaconda3\lib\site-packages)